name: Deploy backend to Azure Web App

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
    DOCKER_REGISTRY_SERVER_URL: bestbankcontregistrydev.azurecr.io
    DOCKER_REGISTRY_NAME: bestbankContRegistryDev
    KEY_VAULT_NAME: BestBank-KV-dev
    BACKEND_WEBAPP_DEV: bestbank-be-dev
    BACKEND_WEBAPP_UAT: bestbank-be-uat
    BACKEND_WEBAPP_PROD: bestbank-be-prod

jobs:
  # build the docker image
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.image-version.outputs.version }}
    # environment:
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Log in to azure"
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Get docker registry credentials"
      uses: Azure/cli@v2.1.0
      with:
        inlineScript: |
            echo "REGISTRY_USERNAME=$(az keyvault secret show --name ${{ env.DOCKER_REGISTRY_NAME }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV
            echo "REGISTRY_PASSWORD=$(az keyvault secret show --name ${{ env.DOCKER_REGISTRY_NAME }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV

    - name: List files in the workspace (Development)
      run: ls -R

    - name: "Login to Docker Registry"
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Set image version
      id: image-version
      run: |
            echo "version=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

    - name: Print images
      run: |
            echo "Images"
            docker images

    - name: Docker Build and Push
      run: |
        docker build . -t ${{ env.DOCKER_REGISTRY_SERVER_URL }}/bestbank-be:${{ steps.image-version.outputs.version }}
        docker push ${{ env.DOCKER_REGISTRY_SERVER_URL }}/bestbank-be:${{ steps.image-version.outputs.version }}



    # - name: Upload Docker image info
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: docker-image
    #     path: |
    #       .dockerignore
    #       Dockerfile

# deploy to dev
#   deploy-dev:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Development'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v4
#       with:
#         name: docker-image

#     - name: "Login to Docker Registry"
#       uses: azure/docker-login@v2
#       with:
#         login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL }}
#         username: ${{ env.REGISTRY_USERNAME }}
#         password: ${{ env.REGISTRY_PASSWORD }}

#     - name: "Deploy"
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         images: ${{env.DOCKER_REGISTRY_SERVER_URL}}/bestbank-be:${{ needs.build.outputs.image-version }}



# # deploy uat
#   deploy-uat:
#     if:  (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     needs: [build, deploy-dev]
#     environment:
#       name: 'UAT'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v4
#       with:
#         name: docker-image

#     - name: "Login to Docker Registry"
#       uses: azure/docker-login@v2
#       with:
#         login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL }}
#         username: ${{ env.REGISTRY_USERNAME }}
#         password: ${{ env.REGISTRY_PASSWORD }}

#     - name: "Deploy"
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         images: ${{env.DOCKER_REGISTRY_SERVER_URL}}/bestbank-be:${{ needs.build.outputs.image-version }}

# # deploy prod
#   deploy-prod:
#     # if:  (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     needs: [build, deploy-uat]
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v4
#       with:
#         name: docker-image

#     - name: "Login to Docker Registry"
#       uses: azure/docker-login@v2
#       with:
#         login-server: ${{ env.DOCKER_REGISTRY_SERVER_URL }}
#         username: ${{ env.REGISTRY_USERNAME }}
#         password: ${{ env.REGISTRY_PASSWORD }}

#     - name: "Deploy"
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         images: ${{env.DOCKER_REGISTRY_SERVER_URL}}/bestbank-be:${{ needs.build.outputs.image-version }}
